spring:
  application:
    # 名称
    name: movies-gateway-xtl
  # 注册到nacos
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.203.133:8848
    # 路由网关配置
    gateway:
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: WEB-SERVICE-XTL
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://web-service-xtl
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Path 设置路径，多个路径可以用逗号隔开，/**是为通配符
            - Path=/test
            # 设置访问方法
            - Method=GET,POST


server:
  port: 9000

logging:
  level:
    org.springframework.cloud.gateway: debug