spring:
  # 组合配置文件，超过一个用","隔开
  profiles:
    active: dev, druid, dubbo, mybatis-plus
  application:
    # 提供者名字
    name: movies-image-xtl
  cloud:
    nacos:
      discovery:
        enabled: true
        # 注册中心ip
        server-addr: 192.168.203.133:8848

server:
  # 设置访问端口
  port: 8091

# 健壮性检查
management:
  endpoints:
    web:
      exposure:
        include: "*"